n = input('Digite algo ')
print('O tipo primitivo desse valor é', type(n))
print('Só tem espaços?', n.isspace())
print('Só tem números?', n.isnumeric())
print('Só tem letras?', n.isalpha())
print('É alphanumérico?', n.isalnum())
print('Está somente em letras maiúsculas?', n.isupper())
print('Está somente em letras minúsculas?', n.islower())
print('Tem letras maiúsculas e minúsculas/é capitalizada?', n.istitle())
